version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: blogurs_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - blogurs_pg_data:/var/lib/postgresql/data
    ports:
      - "5600:5432"
    restart: unless-stopped
  
volumes:
  blogurs_pg_data:
